services:
  core-db:
    image: postgres:17-alpine
    container_name: paul-core-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - core-db-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - paul-network
    restart: always

networks:
  paul-network:
    driver: bridge

volumes:
  core-db-data:
